# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lBmS1hRP8McZIkZ1rgTS4RgF1A7SBKEJ
"""

a = int(input())
b = int(input())
c = int(input())
tot_cost = a + b + c
if (tot_cost > 50):
  dis = 0.1*tot_cost
else:
    dis = 0
tot_cost = tot_cost - dis
print(tot_cost)